// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MedLifeDAL.Entities
{
    public partial class AppUser
    {
        public AppUser()
        {
            AppUserClaims = new HashSet<AppUserClaims>();
            AppUserLogins = new HashSet<AppUserLogins>();
            AppUserRoles = new HashSet<AppUserRoles>();
            AppUserTokens = new HashSet<AppUserTokens>();
            AppoinmentBookingCreatedByNavigation = new HashSet<AppoinmentBooking>();
            AppoinmentBookingDoctor = new HashSet<AppoinmentBooking>();
            AppoinmentBookingModifiedByNavigation = new HashSet<AppoinmentBooking>();
            AppoinmentBookingPatient = new HashSet<AppoinmentBooking>();
            DoctorsCreatedByNavigation = new HashSet<Doctors>();
            DoctorsModifiedByNavigation = new HashSet<Doctors>();
        }

        public Guid Id { get; set; }
        public string UserName { get; set; }
        public string NormalizedUserName { get; set; }
        public string Email { get; set; }
        public string NormalizedEmail { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string ConcurrencyStamp { get; set; }
        public string PhoneNumber { get; set; }
        public bool? PhoneNumberConfirmed { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public DateTimeOffset? LockoutEnd { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
        public string Gender { get; set; }
        public string UserRole { get; set; }

        public virtual Doctors DoctorsIdNavigation { get; set; }
        public virtual ICollection<AppUserClaims> AppUserClaims { get; set; }
        public virtual ICollection<AppUserLogins> AppUserLogins { get; set; }
        public virtual ICollection<AppUserRoles> AppUserRoles { get; set; }
        public virtual ICollection<AppUserTokens> AppUserTokens { get; set; }
        public virtual ICollection<AppoinmentBooking> AppoinmentBookingCreatedByNavigation { get; set; }
        public virtual ICollection<AppoinmentBooking> AppoinmentBookingDoctor { get; set; }
        public virtual ICollection<AppoinmentBooking> AppoinmentBookingModifiedByNavigation { get; set; }
        public virtual ICollection<AppoinmentBooking> AppoinmentBookingPatient { get; set; }
        public virtual ICollection<Doctors> DoctorsCreatedByNavigation { get; set; }
        public virtual ICollection<Doctors> DoctorsModifiedByNavigation { get; set; }
    }
}