// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MedLifeDAL.Entities
{
    public partial class Departments
    {
        public Departments()
        {
            Doctors = new HashSet<Doctors>();
        }

        public int Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<Doctors> Doctors { get; set; }
    }
}