// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace MedLifeDAL.Entities
{
    public partial class usp_GetAllPendingPatientsResult
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public int Age { get; set; }
        public string Gender { get; set; }
        public DateTime AppointmentOn { get; set; }
        public string HealthProblem { get; set; }
        public string others { get; set; }
        public string Status { get; set; }
    }
}
