// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace MedLifeDAL.Entities
{
    public partial class usp_GetAllDoctorsResult
    {
        public string DoctorName { get; set; }
        public string Email { get; set; }
        public int Age { get; set; }
        public string Gender { get; set; }
        public string Department { get; set; }
        public string Qualification { get; set; }
        public int Experience { get; set; }
        public string UniqueImageName { get; set; }
    }
}
